name: 'customer_risk_analytics'
version: '1.0.0'
config-version: 2

profile: 'customer_risk_analytics'

model-paths: ["models"]

models:
  customer_risk_analytics:
    staging:
      +materialized: view
    marts:
      +materialized: table