version: 2

models:
  - name: customer_segmentation
    description: "Customer segmentation"
    columns:
      - name: customer_id
        description: "Unique customer identifier"
        tests:
          - unique
          - not_null
      
      - name: full_name
        description: "Customer full name"
        tests:
          - not_null
      
      - name: email
        description: "Customer email"
        tests:
          - not_null
      
      - name: customer_segment
        description: "Customer segment"
        tests:
          - not_null
          - accepted_values:
              values: ['premium', 'regular', 'new']
      
      - name: value_tier
        description: "Value value classification"
        tests:
          - not_null
          - accepted_values:
              values: ['VIP', 'High Value', 'Medium Value', 'Standard']
      
      - name: total_spent
        description: "Total lifetime value"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
      
      - name: total_orders
        description: "Total number of orders"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
      
      - name: customer_activity_score
        description: "Activity score 0-100"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 100

  - name: fraud_analytics
    description: "Fraud risk analysis"
    columns:
      - name: customer_id
        description: "Unique customer identifier"
        tests:
          - unique
          - not_null
          - relationships:
              to: ref('customer_segmentation')
              field: customer_id
      
      - name: full_name
        description: "Customer full name"
        tests:
          - not_null
      
      - name: risk_level
        description: "Risk level"
        tests:
          - not_null
          - accepted_values:
              values: ['low', 'medium', 'high', 'critical']
      
      - name: composite_risk_score
        description: "Composite risk score 0.0-1.0"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 1
              inclusive: true
      
      - name: action_required
        description: "Recommended action"
        tests:
          - not_null
          - accepted_values:
              values: ['STANDARD', 'ENHANCED_MONITORING', 'MANUAL_REVIEW', 'BLOCK_IMMEDIATELY']
      
      - name: investigation_priority
        description: "Priority level 1-5"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 1
              max_value: 5

  - name: high_value_customers
    description: "High value customers"
    columns:
      - name: customer_id
        description: "Unique customer identifier"
        tests:
          - unique
          - not_null
      
      - name: full_name
        description: "Customer full name"
        tests:
          - not_null
      
      - name: customer_tier
        description: "High-value customer tier classification"
        tests:
          - not_null
          - accepted_values:
              values: ['Tier 1 - VIP', 'Tier 2 - Premium', 'Tier 3 - Gold']
      
      - name: retention_status
        description: "Customer retention risk category"
        tests:
          - not_null
          - accepted_values:
              values: ['New Customer - Retention Risk', 'Stable', 'Low Engagement']
      
      - name: total_spent
        description: "Total lifetime value"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 1000